name: Audit Enforce Repo Rename

on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   schedule:
#     # minute (0 - 59), hour (0 - 23), day of the month (1 - 31), month (1 - 12 or JAN-DEC), day of the week (0 - 6 or SUN-SAT)
#     - cron:  '30 5,17 * * *'

jobs:
  audit-repo-name-changes:
    runs-on: ubuntu-latest
    environment: ci-cd-scripts
    steps:
        
      - name: Print Context
        uses: actions/github-script@v5
        with:
          script: |
            console.log(context)
            
      # CHANGE THE SCRIPT BELOW TO USE AUDIT
      - name: Find Repo Name Changes
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          script: |
            console.log("Querying Audit REST API")
            try {
              await github.rest.repos.createUsingTemplate({
                template_owner: context.payload.organization.login,
                template_repo: templateRepo,
                name: newRepo,
                owner: context.payload.organization.login,
                description: "Test",
                include_all_branches: true,
                private: false
              })
            } catch(err) {
                throw err 
            }
            
            bodySplit = context.payload.issue.body.split("\n")
            console.log("New repository name: " + bodySplit[2])
            console.log("Template Repository: " + bodySplit[6])
            console.log("Team: " + bodySplit[10])
            console.log("Enable Issue: " +  bodySplit[14].includes("X"))
            console.log("Enable Project: " +  bodySplit[18].includes("X"))
            console.log("Allow Squash Merge: " +  bodySplit[22].includes("X"))
            console.log("Allow Forking: " +  bodySplit[26].includes("X"))
            let newRepo = bodySplit[2]
            let templateRepo = bodySplit[6]
            let teams = bodySplit[10].split(",")
            let enableIssue = bodySplit[14].includes("X")
            let enableProject = bodySplit[18].includes("X")
            let enableSquashMerge = bodySplit[22].includes("X")
            let enableForking = bodySplit[26].includes("X")
            
            console.log("New repo: " + newRepo + " Template Repo: " + templateRepo + " Teams: " + teams)
            
            try {
              await github.rest.repos.createUsingTemplate({
                template_owner: context.payload.organization.login,
                template_repo: templateRepo,
                name: newRepo,
                owner: context.payload.organization.login,
                description: "Test",
                include_all_branches: true,
                private: false
              })
            } catch(err) {
                throw err 
            }
            
            try {
              await github.rest.repos.update({
                owner: context.payload.organization.login,
                private: false,
                repo: newRepo,
                has_issues: enableIssue,
                has_projects: enableProject,
                allow_squash_merge: enableSquashMerge
              })
            } catch(err) {
                throw err 
            }
            
            try {
              await github.rest.repos.updateBranchProtection({
                "owner": context.payload.organization.login,
                "repo": newRepo,
                "branch": 'main',
                "required_status_checks": { "strict": true, "contexts": [] },
                "enforce_admins": true,
                "required_pull_request_reviews": {"dismissal_restrictions": {"users":[], "teams":[]}, "dismiss_stale_reviews": false, "require_code_owner_reviews": true, "required_approving_review_count": 1},
                "restrictions" : { "users": [], "teams": [], "apps": [] }
              })
            } catch(err) {
                throw err 
            }
            
            try {
              await github.rest.teams.addOrUpdateRepoPermissionsInOrg({
                org: context.payload.organization.login,
                owner: context.payload.organization.login,
                repo: newRepo,
                team_slug: teams,
                permission: 'admin'
              })
            } catch(err) {
                throw err 
            }
            
            try { 
              await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for creating a repo. Your new repo is available at: https://github.com/' + context.payload.organization.login + "/" + newRepo
             }) 
            } catch(err) {
                throw err
            }
