name: Audit Enforce Repo Rename

on:
  repository_dispatch:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   schedule:
#     # minute (0 - 59), hour (0 - 23), day of the month (1 - 31), month (1 - 12 or JAN-DEC), day of the week (0 - 6 or SUN-SAT)
#     - cron:  '30 5,17 * * *'

jobs:
  audit-repo-name-changes:
    runs-on: ubuntu-latest
    environment: ci-cd-scripts
    steps:
        
      - name: Print Context
        uses: actions/github-script@v5
        with:
          script: |
            console.log(context)
            
      # CHANGE THE SCRIPT BELOW TO USE AUDIT
      - name: Find Repo Name Changes
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          script: |
            console.log("Querying Audit REST API")

